### PR TITLE
Quickfix error with .to!string

### PR DESCRIPTION
**Pull request by pheerai**
As mentioned in #34, this fixes an issue with a compilation error due to a mismatching cast type in an invocation of the `to`-template.

This includes the following changes:
 - Update dependencies
 - use `typeof("")` instead of `string`

The latter is necessary, because else the compiler seems to assume that
`string` is some weird alias for the json-internal string type?!

### CODE REVIEW

**Comment by ghost91-** [comment]
What about using `immutable(char)[]` (which `string` is aliased to)? Have you tried that? To me this would look cleaner than `typeof("")`.

**Comment by pheerai** [comment]
Should work, but on the other hand `string` should do so as well.
I more or less hoped that the quickfix `typeof` will remind me/us that there are still open points to be addressed (it is not normal that `.to!string` gets expanded to `.to!(cast(JSONType)cast(byte)1)`, but I did not find the actual cause yet.

**Comment by pheerai** [comment]
Please re-review.

**Comment by ghost91-** [comment]
I see that you found the reason for `string` being shadowed. This is even better 👍

**Comment by ghost91-** [comment]
fixes #34

**Pull request merged**
